from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, EmailStr, Field


# ------------------------------------------------------------------------------
# Auth & User Schemas
# ------------------------------------------------------------------------------
class UserRegisterRequest(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=8, description="User password (min 8 characters)")
    organization_name: Optional[str] = "Default Organization"


class UserLoginRequest(BaseModel):
    email: EmailStr
    password: str


class UserOut(BaseModel):
    id: str
    email: EmailStr
    organization_name: Optional[str]
    is_active: bool
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserOut


class ApiKeyCreateRequest(BaseModel):
    name: str = Field("Default API Key", max_length=100)


class ApiKeyOut(BaseModel):
    id: str
    key_prefix: str
    name: str
    is_active: bool
    created_at: datetime
    last_used_at: Optional[datetime]

    model_config = ConfigDict(from_attributes=True)


class ApiKeyCreatedResponse(ApiKeyOut):
    api_key: str = Field(..., description="Plaintext API key - shown only once upon creation")


# ------------------------------------------------------------------------------
# Trace & Ingestion Schemas
# ------------------------------------------------------------------------------
class ToolCallRecord(BaseModel):
    tool_name: str
    arguments: Optional[Dict[str, Any]] = None
    output: Optional[Any] = None
    error: Optional[str] = None


class TraceIngestRequest(BaseModel):
    trace_id: str = Field(..., description="Root trace ID linking multi-step agent workflows")
    span_id: Optional[str] = Field(None, description="Unique span ID for this specific step/call")
    parent_span_id: Optional[str] = Field(None, description="Parent span ID for call tree reconstruction")
    agent_name: str = Field("default_agent", description="Name of the agent or pipeline component")
    task_type: str = Field("general", description="Classification of task, e.g. rag, code_gen, routing")
    model_name: str = Field("unknown", description="Model invoked, e.g. gpt-4o, llama-3.3-70b")

    input_query: str = Field(..., description="Original user prompt or input prompt to agent")
    context: Optional[str] = Field(None, description="Retrieved context, RAG passages, or reference data")
    output_result: str = Field(..., description="Raw output generated by the LLM/agent")

    latency_ms: float = Field(0.0, ge=0.0, description="Latency in milliseconds")
    input_tokens: int = Field(0, ge=0, description="Input/prompt token count")
    output_tokens: int = Field(0, ge=0, description="Completion/output token count")
    cost_usd: Optional[float] = Field(None, ge=0.0, description="Computed or tracked cost in USD")

    status: Optional[str] = Field("success", description="Status of the call: 'success' or 'failed'")
    failure_reasons: Optional[List[str]] = Field(default_factory=list, description="Explicitly logged failures")

    # Observability & deterministic rule verification metadata
    step_index: Optional[int] = Field(0, ge=0)
    max_steps_allowed: Optional[int] = Field(None, description="Configured step budget to verify step overrun")
    expected_schema: Optional[Dict[str, Any]] = Field(None, description="Expected JSON Schema for output validation")
    tool_calls: Optional[List[ToolCallRecord]] = Field(None, description="Sequence of tool calls for loop detection")
    metadata_json: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Arbitrary custom metadata")


class TraceIngestResponse(BaseModel):
    status: str
    trace_id: str
    span_id: str
    eval_status: str
    detected_failures: List[str] = []
    message: Optional[str] = None


class EvaluationOut(BaseModel):
    id: str
    trace_record_id: str
    hallucination_score: float
    faithfulness_score: float
    relevance_score: float
    claims_extracted: Optional[List[Any]] = []
    verdict: str
    eval_status: str
    judge_model: Optional[str] = None
    eval_latency_ms: Optional[float] = None
    reasoning: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class TraceDetailOut(BaseModel):
    id: str
    trace_id: str
    span_id: str
    parent_span_id: Optional[str]
    agent_name: str
    task_type: str
    model_name: str
    input_query: str
    context: Optional[str]
    output_result: str
    latency_ms: float
    input_tokens: int
    output_tokens: int
    cost_usd: float
    status: str
    failure_reasons: Optional[List[str]]
    step_index: Optional[int]
    metadata_json: Optional[Dict[str, Any]]
    created_at: datetime
    evaluation: Optional[EvaluationOut] = None

    model_config = ConfigDict(from_attributes=True)


class TraceTreeNode(BaseModel):
    span: TraceDetailOut
    children: List["TraceTreeNode"] = []


class TraceTreeResponse(BaseModel):
    trace_id: str
    root_spans: List[TraceTreeNode]
    total_spans: int
    total_latency_ms: float
    total_cost_usd: float
    has_failures: bool


# ------------------------------------------------------------------------------
# Routing Optimizer Schemas
# ------------------------------------------------------------------------------
class RoutingRecommendationRequest(BaseModel):
    task_type: str = Field(..., description="Target task type (e.g. summarization, coding, support)")
    min_quality_bar: float = Field(0.80, ge=0.0, le=1.0, description="Minimum acceptable quality/relevance score")
    max_latency_ms: Optional[float] = Field(None, description="Optional maximum latency SLA")


class RoutingRecommendationResponse(BaseModel):
    task_type: str
    recommended_model: str
    estimated_cost_per_1k_tokens: float
    historical_quality_score: float
    historical_avg_latency_ms: float
    sample_count: int
    escalation_triggered: bool
    escalation_reason: Optional[str] = None
    fallback_model: Optional[str] = None
    confidence_note: str


# ------------------------------------------------------------------------------
# Dashboard & Analytics Schemas
# ------------------------------------------------------------------------------
class CostBreakdownItem(BaseModel):
    dimension: str
    cost_usd: float
    token_count: int
    call_count: int


class CostAnalyticsResponse(BaseModel):
    total_cost_usd: float
    total_tokens: int
    total_calls: int
    by_agent: List[CostBreakdownItem]
    by_model: List[CostBreakdownItem]
    by_task: List[CostBreakdownItem]
    daily_trend: List[Dict[str, Any]]


class FailureAnalyticsResponse(BaseModel):
    total_calls: int
    failed_calls: int
    failure_rate_percent: float
    failures_by_type: Dict[str, int]
    affected_agents: List[Dict[str, Any]]
    recent_failures: List[TraceDetailOut]


class BottleneckItem(BaseModel):
    agent_name: str
    model_name: str
    avg_latency_ms: float
    p95_latency_ms: float
    call_count: int


class TrendsAnalyticsResponse(BaseModel):
    avg_latency_ms: float
    p95_latency_ms: float
    avg_faithfulness_score: float
    avg_relevance_score: float
    hallucination_rate_percent: float
    bottlenecks: List[BottleneckItem]
    time_series: List[Dict[str, Any]]


# ------------------------------------------------------------------------------
# Alert Schemas
# ------------------------------------------------------------------------------
class AlertRuleCreate(BaseModel):
    name: str = Field(..., max_length=120)
    metric: str = Field(..., description="hallucination_rate, error_rate, or cost_threshold")
    threshold: float = Field(..., description="Numeric trigger threshold")
    window_minutes: int = Field(60, ge=1, le=10080)
    target_email: EmailStr
    is_active: bool = True


class AlertRuleOut(BaseModel):
    id: str
    name: str
    metric: str
    threshold: float
    window_minutes: int
    target_email: str
    is_active: bool
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AlertHistoryOut(BaseModel):
    id: str
    rule_id: Optional[str]
    metric: str
    triggered_value: float
    threshold: float
    message: str
    sent_to: str
    status: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


# ------------------------------------------------------------------------------
# Root-Cause Diagnosis & AI Remediation Schemas
# ------------------------------------------------------------------------------
class TraceDiagnosisResponse(BaseModel):
    trace_id: str
    agent_name: str
    status: str
    severity: str = Field(..., description="CRITICAL, HIGH, MEDIUM, or LOW")
    primary_issue: str
    root_cause_summary: str
    detailed_analysis: str
    recommended_prompt_patch: str
    recommended_code_patch: Optional[str] = None
    prevention_guide: str
    diagnosed_by: str = "agentops-ai-diagnoser"
    confidence_score: float = 0.95


# ------------------------------------------------------------------------------
# Live Web Fact-Checking & Grounding Schemas
# ------------------------------------------------------------------------------
class FactCheckCitation(BaseModel):
    title: str = ""
    url: str = ""
    snippet: str = ""
    supports: bool = True


class FactCheckClaim(BaseModel):
    claim: str = ""
    status: str = "SUPPORTED"
    evidence: str = ""


class FactCheckResponse(BaseModel):
    trace_id: str
    verdict: str = "VERIFIED"
    grounding_score: float = 0.90
    summary: str = ""
    verified_answer: str = ""
    search_query: str = ""
    latency_ms: float = 0.0
    judge_model: str = "groq:openai/gpt-oss-120b"
    citations: List[FactCheckCitation] = []
    claims_checked: List[FactCheckClaim] = []


# ------------------------------------------------------------------------------
# Security, Prompt Injection & Red-Team Audit Schemas
# ------------------------------------------------------------------------------
class RedTeamProbe(BaseModel):
    probe_id: str = "OWASP-LLM01"
    name: str = ""
    payload_tested: str = ""
    agent_defense: str = ""
    status: str = "PASSED"
    threat_vector: str = ""


class SecurityAuditResponse(BaseModel):
    trace_id: str
    agent_name: str
    is_live_test: bool = False
    server_online: bool = True
    target_url: Optional[str] = None
    overall_security_score: float = 100.0
    safety_grade: str = "A+"
    threat_level: str = "SAFE"
    prompt_injection_status: str = "NONE"
    pii_leakage_status: str = "NO_LEAKAGE"
    system_prompt_leakage: str = "PROTECTED"
    role_boundary_status: str = "MAINTAINED"
    executive_summary: str = ""
    test_probes_executed: List[RedTeamProbe] = []
    vulnerabilities_found: List[str] = []
    remediation_guardrail: str = ""
    latency_ms: float = 0.0
    audited_by: str = "agentops-security-engine"
    heuristic_flags: Optional[Dict[str, Any]] = None

